### ISSUE TITLE
更好地引导读者

### ISSUE THREAD

**Issue by BobJackson** [DocsHome/microservices#9]
我看完了后一个整体感受：译者的文笔还是挺有功底的，不然我看整本英文的书，还是比较花时间的，而且极容易分散注意力到个别单词上。
这本书主要说明了写作意图在：“我希望这本电子书能够让您对微服务架构、其优点和缺点以及何时使用它有很好的了解。”最后，我个人觉得，相比于单体架构应用，随着时间推移，微服务的数量将会增长，您的开发团队的灵活性和速度也同样会增加，这是微服务的最迷人的魅力的地方。
你可以做一个序，比如“译者序”，这样可能就更完美了。
最后，全书，“您”这个称呼，给读者的感受，真的很奇特。(๑╹◡╹)ﾉ"""

**Comment by oopsguy** [comment]
@BobJackson 嘿嘿，感谢您的支持，当初翻译这几篇文章也是出于学习和分享的目的，做得比较业余，整体内容也比较少，自己需要提升的地方还有很多。您的建议也不错，不过加上显得太正式了，我倒是希望有一天有能力翻译一本书，有机会出版的话，倒是可以加上，哈哈，说笑了😀。
